import { CreativeSpeciesEnum } from './creative-species.enum';

export const HABITS_DARK = [
  'Stimulated By Constraints',
  'Solo Creator',
  'Routine Seeker',
  'Public',
  'Private',
  'Outwardly Inspired',
  'Novelty Seeker',
  'NonKinetic',
  'Noise/Music',
  'Night Owl',
  'Make It Happen',
  'Let It Happen',
  'Inwardly Inspired',
  'Comfortable with Mess',
  'Urban',
];

export const HABITS_BY_CLUSTERS = {
  [CreativeSpeciesEnum.MONO_ROUTINUS]: [
    'Risk Averse',
    'Routine Seeker',
    'Hate Distractions',
    'Monotasker',
    'Make It Happen',
    'Solo Creator',
    'Private',
    'Externally Motivated',
    'Rational',
    'Slow Paced',
    'Stimulated By Constraints',
    'Urban',
    'Specialist',
  ],
  [CreativeSpeciesEnum.YOLO_CHAOTIS]: [
    'Novelty Seeker',
    'Risk Friendly',
    'Stifled By Constraints',
    'Internally Motivated',
    'Multitasker',
    'Let It Happen',
    'Inwardly Inspired',
    'Controlled Chaos',
    'Intuitive',
    'Noise/Music',
    'Fast Paced',
  ],
  [CreativeSpeciesEnum.SOCIALIS_ADVENTUROUS]: [
    'Collaborator',
    'Risk Friendly',
    'Multitasker',
    'Reframer',
    'Kinetic',
    'Fast Paced',
    'Early Bird',
    'Self-Assured',
    'Public',
  ],
  [CreativeSpeciesEnum.FOCUS_MONONOVOUS]: [
    'Novelty Seeker',
    'Monotasker',
    'Stifled By Constraints',
    'Hate Distractions',
    'Nature',
  ],
  [CreativeSpeciesEnum.NOVO_GREGARIOUS]: [
    'Novelty Seeker',
    'Externally Motivated',
    'Outwardly Inspired',
    'Collaborator',
    'Noise/Music',
    'Stimulated By Constraints',
    'Love Distractions',
    'Public',
  ],
  [CreativeSpeciesEnum.SUI_INSPIRA]: [
    'Routine Seeker',
    'Private',
    'Internally Motivated',
    'Solo Creator',
    'Inwardly Inspired',
  ],
  [CreativeSpeciesEnum.SOLO_NOCTUS]: [
    'Stifled By Constraints',
    'Internally Motivated',
    'Solo Creator',
    'Night Owl',
    'Risk Averse',
    'Make It Happen',
    'Tenacious',
    'NonKinetic',
    'Urban',
    'Love Distractions',
    'Specialist',
  ],
  [CreativeSpeciesEnum.RARE_BREED]: [],
};
