import { CreativeSpeciesEnum } from './creative-species.enum';

export const HABITS_DARK = [
  'Stimulated By Constraints',
  'Solo Creator',
  'Routine-Seeker',
  'Public Spaces',
  'Private Spaces',
  'Outwardly Inspired',
  'Novelty-Seeker',
  'NonKinetic',
  'Noise/Music',
  'Night Owl',
  'Make It Happen',
  'Let It Happen',
  'Inwardly Inspired',
  'Comforting Mess',
  'Nature-Agnostic',
];

export const HABITS_BY_CLUSTERS = {
  [CreativeSpeciesEnum.MONO_ROUTINUS]: [
    'Risk-Averse',
    'Routine-Seeker',
    'Dislike Distractions',
    'Monotasker',
    'Make It Happen',
    'Solo Creator',
    'Private',
    'Externally Motivated',
    'Rational',
    'Slow-Paced',
    'Stimulated By Constraints',
    'Nature-Agnostic',
    'Specialist',
  ],
  [CreativeSpeciesEnum.YOLO_CHAOTIS]: [
    'Novelty-Seeker',
    'Risk-Friendly',
    'Stifled By Constraints',
    'Internally Motivated',
    'Multitasker',
    'Let It Happen',
    'Inwardly Inspired',
    'Comforting Mess',
    'Intuitive',
    'Noise/Music',
    'Fast-Paced',
  ],
  [CreativeSpeciesEnum.SOCIALIS_ADVENTUROUS]: [
    'Collaborator',
    'Risk-Friendly',
    'Multitasker',
    'Reframer',
    'Kinetic',
    'Fast-Paced',
    'Early Bird',
    'Self-Assured',
    'Public Spaces',
  ],
  [CreativeSpeciesEnum.FOCUS_MONONOVOUS]: [
    'Novelty-Seeker',
    'Monotasker',
    'Stifled By Constraints',
    'Dislike Distractions',
    'Nature-Lover',
  ],
  [CreativeSpeciesEnum.NOVO_GREGARIOUS]: [
    'Novelty-Seeker',
    'Externally Motivated',
    'Outwardly Inspired',
    'Collaborator',
    'Noise/Music',
    'Stimulated By Constraints',
    'Love Distractions',
    'Public Spaces',
  ],
  [CreativeSpeciesEnum.SUI_INSPIRA]: [
    'Routine-Seeker',
    'Private Spaces',
    'Internally Motivated',
    'Solo Creator',
    'Inwardly Inspired',
  ],
  [CreativeSpeciesEnum.SOLO_NOCTUS]: [
    'Stifled By Constraints',
    'Internally Motivated',
    'Solo Creator',
    'Night Owl',
    'Risk-Averse',
    'Make It Happen',
    'Tenacious',
    'NonKinetic',
    'Nature-Agnostic',
    'Love Distractions',
    'Specialist',
  ],
  [CreativeSpeciesEnum.RARE_BREED]: [],
};

export enum HabitViewEnum {
  INTRO = 1,
  EXPLORE = 2,
  DIGGING = 3,
  DOWNLOAD = 4,
}
